pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'us-west-1'
    }
    stages{
        stage('Checkout SCM'){
            steps{
                script{
                    //Generate  using pipeline syntax
                }
            }
        }
         stage('Initializing Terraform'){
            steps{
                script{
                    dir('install-docker'){
                         sh 'terraform init'
                    }
                }
            }
        }
       
        stage('Validating Terraform'){
            steps{
                script{
                    dir('install-docker'){
                         sh 'terraform validate'
                    }
                }
            }
        }
        stage('Previewing the infrastructure'){
            steps{
                script{
                    dir('install-docker'){
                         sh 'terraform plan'
                    }
            
                }
            }
        }
        stage('Creating an EC2 instance'){
            steps{
                script{
                    dir('install-docker'){
                         sh 'terraform apply'
                    }
                }
            }
        }
    
    }
}